### ISSUE TITLE
Nudges to do prophecy and to give feedback

### ISSUE THREAD

**Issue by castellanocj1** [djotaku/prophecypracticum_django#22]
Also, I'd like a feature which "nudges" the prophets who haven't done their PP by like 5 days into the practicum. Like an email is sent to them.  Also, if a prophecy doesn't have feedback after like 1 day, an email reminder should be sent to them.

**Comment by djotaku** [comment]
This is going to require for me to learn Celery. Will probably do this later than other asks rather than hold everything up while I learn that.

**Comment by djotaku** [comment]
On the other hand, Celery may be a bit much for this. Will have to do further research.

**Comment by djotaku** [comment]
Follow the advice given at https://www.reddit.com/r/django/comments/tfnjf8/django_app_very_tiny_so_instead_of_using_celery/
