### ISSUE TITLE
Reorganize feedback page

### ISSUE THREAD

**Issue by castellanocj1** [djotaku/prophecypracticum_django#24]
Also, Trying to link up who has given Prophecy Feedback and who hasn't is very challenging. Could the prophecy feedback view look more like the prophecy view on the admin page?

**Comment by djotaku** [comment]
What is it about the prophecy view page that you want to appear on the feedback page?

**Comment by djotaku** [comment]
This *might* end up being solved by #26 - we'll see...

**Comment by djotaku** [comment]
fixed back when I did #26
